# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 194276782d2b79e409eec13b4c605fd00ba46635b5f74e75436f185e21c07187e7eeba35b2c36196066c278a93a95edeefdf38c1433e669c5a6856cbcfb9a5ec

test:
  secret_key_base: 5383270e7c52e8540abf3c728261cba8a38d9b7067fe37e6c916d5f5a40f8fa7d3b7ffd2e839168e889e6d54eb4047efb6b92a4ba28676fac0d709812ef2ec1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
